--- https://programmers.co.kr/learn/courses/30/lessons/59042#
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS 
WHERE ANIMAL_OUTS.ANIMAL_ID 
NOT IN (
    SELECT ANIMAL_INS.ANIMAL_ID
    FROM ANIMAL_INS
)