SELECT ANIMAL_INS.ANIMAL_ID , ANIMAL_INS.ANIMAL_TYPE,  ANIMAL_INS.NAME
FROM ANIMAL_INS
JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE <> ANIMAL_OUTS.SEX_UPON_OUTCOME
